dist: xenial
language: minimal
addons:
  apt:
    update: true
    packages:
      - libdata-dump-perl
      - libdata-uuid-perl
      - libfile-copy-recursive-perl
      - libio-captureoutput-perl
      - libpath-tiny-perl
      - libseccomp2
      - libsort-versions-perl
      - libstring-shellquote-perl
      - libtemplate-perl
      - libyaml-libyaml-perl
      - runc
script:
  - gpg --keyring keyring/cmake.gpg --no-default-keyring -k
  - gpg --no-default-keyring --keyring keyring/cmake.gpg --keyserver pool.sks-keyservers.net --recv-keys 2D2CEF1034921684
  - gpg --keyring keyring/cmake.gpg --no-default-keyring -k
  - make alpha-android-armv7
